[phases.setup]
nixPkgs = ["chromium", "nss", "nspr", "atk", "cups", "libdrm", "dbus", "libxkbcommon", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXrandr", "xorg.libXext", "xorg.libxcb", "xorg.libX11", "mesa"]

[phases.build]
cmds = ["pip install -r requirements.txt"]